macro_rules! build_function_list {
    ($type:ident, $version:expr $(, $extra_field:ident : $extra_value:expr )* $(,)?) => {
        $type {
            version: $version,
            C_Initialize: Some($crate::dispatch::general::c_initialize),
            C_Finalize: Some($crate::dispatch::general::c_finalize),
            C_GetInfo: Some($crate::dispatch::general::c_get_info),
            C_GetFunctionList: Some($crate::C_GetFunctionList),
            C_GetSlotList: Some($crate::dispatch::general::c_get_slot_list),
            C_GetSlotInfo: Some($crate::dispatch::general::c_get_slot_info),
            C_GetTokenInfo: Some($crate::dispatch::general::c_get_token_info),
            C_GetMechanismList: Some($crate::dispatch::general::c_get_mechanism_list),
            C_GetMechanismInfo: Some($crate::dispatch::general::c_get_mechanism_info),
            C_InitToken: Some($crate::dispatch::general::c_init_token),
            C_InitPIN: Some($crate::dispatch::general::c_init_pin),
            C_SetPIN: Some($crate::dispatch::general::c_set_pin),
            C_OpenSession: Some($crate::dispatch::general::c_open_session),
            C_CloseSession: Some($crate::dispatch::general::c_close_session),
            C_CloseAllSessions: Some($crate::dispatch::general::c_close_all_sessions),
            C_GetSessionInfo: Some($crate::dispatch::general::c_get_session_info),
            C_GetOperationState: Some($crate::dispatch::general::c_get_operation_state),
            C_SetOperationState: Some($crate::dispatch::general::c_set_operation_state),
            C_Login: Some($crate::dispatch::general::c_login),
            C_Logout: Some($crate::dispatch::general::c_logout),
            C_CreateObject: Some($crate::dispatch::general::c_create_object),
            C_CopyObject: Some($crate::dispatch::general::c_copy_object),
            C_DestroyObject: Some($crate::dispatch::general::c_destroy_object),
            C_GetObjectSize: Some($crate::dispatch::general::c_get_object_size),
            C_GetAttributeValue: Some($crate::dispatch::general::c_get_attribute_value),
            C_SetAttributeValue: Some($crate::dispatch::general::c_set_attribute_value),
            C_FindObjectsInit: Some($crate::dispatch::general::c_find_objects_init),
            C_FindObjects: Some($crate::dispatch::general::c_find_objects),
            C_FindObjectsFinal: Some($crate::dispatch::general::c_find_objects_final),
            C_EncryptInit: Some($crate::dispatch::general::c_encrypt_init),
            C_Encrypt: Some($crate::dispatch::general::c_encrypt),
            C_EncryptUpdate: Some($crate::dispatch::general::c_encrypt_update),
            C_EncryptFinal: Some($crate::dispatch::general::c_encrypt_final),
            C_DecryptInit: Some($crate::dispatch::general::c_decrypt_init),
            C_Decrypt: Some($crate::dispatch::general::c_decrypt),
            C_DecryptUpdate: Some($crate::dispatch::general::c_decrypt_update),
            C_DecryptFinal: Some($crate::dispatch::general::c_decrypt_final),
            C_DigestInit: Some($crate::dispatch::general::c_digest_init),
            C_Digest: Some($crate::dispatch::general::c_digest),
            C_DigestUpdate: Some($crate::dispatch::general::c_digest_update),
            C_DigestKey: Some($crate::dispatch::general::c_digest_key),
            C_DigestFinal: Some($crate::dispatch::general::c_digest_final),
            C_SignInit: Some($crate::dispatch::general::c_sign_init),
            C_Sign: Some($crate::dispatch::general::c_sign),
            C_SignUpdate: Some($crate::dispatch::general::c_sign_update),
            C_SignFinal: Some($crate::dispatch::general::c_sign_final),
            C_SignRecoverInit: Some($crate::dispatch::general::c_sign_recover_init),
            C_SignRecover: Some($crate::dispatch::general::c_sign_recover),
            C_VerifyInit: Some($crate::dispatch::general::c_verify_init),
            C_Verify: Some($crate::dispatch::general::c_verify),
            C_VerifyUpdate: Some($crate::dispatch::general::c_verify_update),
            C_VerifyFinal: Some($crate::dispatch::general::c_verify_final),
            C_VerifyRecoverInit: Some($crate::dispatch::general::c_verify_recover_init),
            C_VerifyRecover: Some($crate::dispatch::general::c_verify_recover),
            C_DigestEncryptUpdate: Some($crate::dispatch::general::c_digest_encrypt_update),
            C_DecryptDigestUpdate: Some($crate::dispatch::general::c_decrypt_digest_update),
            C_SignEncryptUpdate: Some($crate::dispatch::general::c_sign_encrypt_update),
            C_DecryptVerifyUpdate: Some($crate::dispatch::general::c_decrypt_verify_update),
            C_GenerateKey: Some($crate::dispatch::general::c_generate_key),
            C_GenerateKeyPair: Some($crate::dispatch::general::c_generate_key_pair),
            C_WrapKey: Some($crate::dispatch::general::c_wrap_key),
            C_UnwrapKey: Some($crate::dispatch::general::c_unwrap_key),
            C_DeriveKey: Some($crate::dispatch::general::c_derive_key),
            C_SeedRandom: Some($crate::dispatch::general::c_seed_random),
            C_GenerateRandom: Some($crate::dispatch::general::c_generate_random),
            C_GetFunctionStatus: Some($crate::dispatch::general::c_get_function_status),
            C_CancelFunction: Some($crate::dispatch::general::c_cancel_function),
            C_WaitForSlotEvent: Some($crate::dispatch::general::c_wait_for_slot_event),
            $($extra_field: $extra_value,)*
        }
    };
}

macro_rules! build_function_list_3_x {
    ($type:ident, $version:expr $(, $extra_field:ident : $extra_value:expr )* $(,)?) => {
        $crate::function_registry::build_function_list!(
            $type,
            $version,
            C_GetInterfaceList: Some($crate::C_GetInterfaceList),
            C_GetInterface: Some($crate::C_GetInterface),
            C_LoginUser: Some($crate::dispatch::general::c_login_user),
            C_SessionCancel: Some($crate::dispatch::general::c_session_cancel),
            C_MessageEncryptInit: Some($crate::dispatch::general::c_message_encrypt_init),
            C_EncryptMessage: Some($crate::dispatch::general::c_encrypt_message),
            C_EncryptMessageBegin: Some($crate::dispatch::general::c_encrypt_message_begin),
            C_EncryptMessageNext: Some($crate::dispatch::general::c_encrypt_message_next),
            C_MessageEncryptFinal: Some($crate::dispatch::general::c_message_encrypt_final),
            C_MessageDecryptInit: Some($crate::dispatch::general::c_message_decrypt_init),
            C_DecryptMessage: Some($crate::dispatch::general::c_decrypt_message),
            C_DecryptMessageBegin: Some($crate::dispatch::general::c_decrypt_message_begin),
            C_DecryptMessageNext: Some($crate::dispatch::general::c_decrypt_message_next),
            C_MessageDecryptFinal: Some($crate::dispatch::general::c_message_decrypt_final),
            C_MessageSignInit: Some($crate::dispatch::general::c_message_sign_init),
            C_SignMessage: Some($crate::dispatch::general::c_sign_message),
            C_SignMessageBegin: Some($crate::dispatch::general::c_sign_message_begin),
            C_SignMessageNext: Some($crate::dispatch::general::c_sign_message_next),
            C_MessageSignFinal: Some($crate::dispatch::general::c_message_sign_final),
            C_MessageVerifyInit: Some($crate::dispatch::general::c_message_verify_init),
            C_VerifyMessage: Some($crate::dispatch::general::c_verify_message),
            C_VerifyMessageBegin: Some($crate::dispatch::general::c_verify_message_begin),
            C_VerifyMessageNext: Some($crate::dispatch::general::c_verify_message_next),
            C_MessageVerifyFinal: Some($crate::dispatch::general::c_message_verify_final),
            $($extra_field: $extra_value,)*
        )
    };
}

pub(crate) use build_function_list;
pub(crate) use build_function_list_3_x;
