// @generated by scripts/gen-historical-mechanism-flags.py
// Source: OASIS PKCS#11 historical-mechanisms spec (pkcs11-hist v3.0)
// function table; numeric values from the 2.40 published header.
// DO NOT EDIT BY HAND — re-run the generator to refresh.
//
// 105 historical mechanisms grounded; 0 lacked a 2.40 value and were skipped.
#![allow(clippy::unreadable_literal)]

use pkcs11_proxy_ng_types::{CkMechanismFlags, CkMechanismType};

/// Workflow flags for a legacy mechanism, transcribed from the
/// historical-mechanisms spec. `None` for mechanisms the spec does
/// not define (the mock keeps rejecting those).
pub(super) fn historical_workflow_flags(mech: CkMechanismType) -> Option<u64> {
    Some(match mech.0 {
        // CKM_BATON_CBC128
        0x00001033 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_BATON_COUNTER
        0x00001034 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_BATON_ECB128
        0x00001031 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_BATON_ECB96
        0x00001032 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_BATON_KEY_GEN
        0x00001030 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_BATON_SHUFFLE
        0x00001035 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_BATON_WRAP
        0x00001036 => CkMechanismFlags::WRAP | CkMechanismFlags::UNWRAP,
        // CKM_CAST128_CBC
        0x00000322 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST128_CBC_PAD
        0x00000325 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST128_ECB
        0x00000321 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST128_KEY_GEN
        0x00000320 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_CAST128_MAC
        0x00000323 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_CAST128_MAC_GENERAL
        0x00000324 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_CAST3_CBC
        0x00000312 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST3_CBC_PAD
        0x00000315 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST3_ECB
        0x00000311 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST3_KEY_GEN
        0x00000310 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_CAST3_MAC
        0x00000313 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_CAST3_MAC_GENERAL
        0x00000314 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_CAST_CBC
        0x00000302 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST_CBC_PAD
        0x00000305 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST_ECB
        0x00000301 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CAST_KEY_GEN
        0x00000300 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_CAST_MAC
        0x00000303 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_CAST_MAC_GENERAL
        0x00000304 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_CDMF_CBC
        0x00000142 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CDMF_CBC_PAD
        0x00000145 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CDMF_ECB
        0x00000141 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_CDMF_KEY_GEN
        0x00000140 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_CDMF_MAC
        0x00000143 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_CDMF_MAC_GENERAL
        0x00000144 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_DES_CBC
        0x00000122 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_DES_CBC_PAD
        0x00000125 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_DES_ECB
        0x00000121 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_DES_KEY_GEN
        0x00000120 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_DES_MAC
        0x00000123 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_DES_MAC_GENERAL
        0x00000124 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_FASTHASH
        0x00001070 => CkMechanismFlags::DIGEST,
        // CKM_FORTEZZA_TIMESTAMP
        0x00001020 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_IDEA_CBC
        0x00000342 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_IDEA_CBC_PAD
        0x00000345 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_IDEA_ECB
        0x00000341 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_IDEA_KEY_GEN
        0x00000340 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_IDEA_MAC
        0x00000343 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_IDEA_MAC_GENERAL
        0x00000344 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_JUNIPER_CBC128
        0x00001062 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_JUNIPER_COUNTER
        0x00001063 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_JUNIPER_ECB128
        0x00001061 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_JUNIPER_KEY_GEN
        0x00001060 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_JUNIPER_SHUFFLE
        0x00001064 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_JUNIPER_WRAP
        0x00001065 => CkMechanismFlags::WRAP | CkMechanismFlags::UNWRAP,
        // CKM_KEA_KEY_DERIVE
        0x00001011 => CkMechanismFlags::DERIVE,
        // CKM_KEA_KEY_PAIR_GEN
        0x00001010 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_KEY_WRAP_LYNKS
        0x00000400 => CkMechanismFlags::WRAP | CkMechanismFlags::UNWRAP,
        // CKM_KEY_WRAP_SET_OAEP
        0x00000401 => CkMechanismFlags::WRAP | CkMechanismFlags::UNWRAP,
        // CKM_MD2
        0x00000200 => CkMechanismFlags::DIGEST,
        // CKM_MD2_HMAC
        0x00000201 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_MD2_HMAC_GENERAL
        0x00000202 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_MD2_KEY_DERIVATION
        0x00000391 => CkMechanismFlags::DERIVE,
        // CKM_MD5
        0x00000210 => CkMechanismFlags::DIGEST,
        // CKM_MD5_HMAC
        0x00000211 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_MD5_HMAC_GENERAL
        0x00000212 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_MD5_KEY_DERIVATION
        0x00000390 => CkMechanismFlags::DERIVE,
        // CKM_PBA_SHA1_WITH_SHA1_HMAC
        0x000003c0 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_MD2_DES_CBC
        0x000003a0 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_MD5_CAST128_CBC
        0x000003a4 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_MD5_CAST3_CBC
        0x000003a3 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_MD5_CAST_CBC
        0x000003a2 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_MD5_DES_CBC
        0x000003a1 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_SHA1_CAST128_CBC
        0x000003a5 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_SHA1_RC2_128_CBC
        0x000003aa => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_SHA1_RC2_40_CBC
        0x000003ab => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_SHA1_RC4_128
        0x000003a6 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_PBE_SHA1_RC4_40
        0x000003a7 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_RC2_CBC
        0x00000102 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_RC2_CBC_PAD
        0x00000105 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_RC2_ECB
        0x00000101 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_RC2_KEY_GEN
        0x00000100 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_RC2_MAC
        0x00000103 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_RC2_MAC_GENERAL
        0x00000104 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_RC4
        0x00000111 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_RC4_KEY_GEN
        0x00000110 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_RC5_CBC
        0x00000332 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_RC5_CBC_PAD
        0x00000335 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_RC5_ECB
        0x00000331 => {
            CkMechanismFlags::ENCRYPT
                | CkMechanismFlags::DECRYPT
                | CkMechanismFlags::WRAP
                | CkMechanismFlags::UNWRAP
        }
        // CKM_RC5_KEY_GEN
        0x00000330 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_RC5_MAC
        0x00000333 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_RC5_MAC_GENERAL
        0x00000334 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_RIPEMD128
        0x00000230 => CkMechanismFlags::DIGEST,
        // CKM_RIPEMD128_HMAC
        0x00000231 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_RIPEMD128_HMAC_GENERAL
        0x00000232 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_RIPEMD160
        0x00000240 => CkMechanismFlags::DIGEST,
        // CKM_RIPEMD160_HMAC
        0x00000241 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_RIPEMD160_HMAC_GENERAL
        0x00000242 => CkMechanismFlags::SIGN | CkMechanismFlags::VERIFY,
        // CKM_SKIPJACK_CBC64
        0x00001002 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_SKIPJACK_CFB16
        0x00001006 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_SKIPJACK_CFB32
        0x00001005 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_SKIPJACK_CFB64
        0x00001004 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_SKIPJACK_CFB8
        0x00001007 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_SKIPJACK_ECB64
        0x00001001 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_SKIPJACK_KEY_GEN
        0x00001000 => CkMechanismFlags::GENERATE | CkMechanismFlags::GENERATE_KEY_PAIR,
        // CKM_SKIPJACK_OFB64
        0x00001003 => CkMechanismFlags::ENCRYPT | CkMechanismFlags::DECRYPT,
        // CKM_SKIPJACK_PRIVATE_WRAP
        0x00001009 => CkMechanismFlags::WRAP | CkMechanismFlags::UNWRAP,
        // CKM_SKIPJACK_RELAYX
        0x0000100a => CkMechanismFlags::WRAP | CkMechanismFlags::UNWRAP,
        // CKM_SKIPJACK_WRAP
        0x00001008 => CkMechanismFlags::WRAP | CkMechanismFlags::UNWRAP,
        _ => return None,
    })
}
