#!/usr/bin/env python3
"""Generate the mock's historical-mechanism workflow-flags table.

Parses the OASIS *historical mechanisms* spec (pkcs11-hist) — the
Mechanisms-vs-Functions table — plus the 2.40 header (for numeric
values) and emits a committed Rust table used by the mock to accept
legacy mechanisms (SKIPJACK/BATON/JUNIPER/KEA, RC2/RC4/RC5, CAST, IDEA,
GOST, MD2/MD5, RIPEMD, …) whose workflow prose the *current working*
spec dropped.

Source-grounded, no guessing: every flag comes from the historical
spec's own function table; the generated table is committed so CI needs
neither the spec nor this script (identical in principle to baking
cryptoki_sys CKM_* values). Re-run only when the historical spec source
changes.

Usage:
    PKCS11_PROXY_NG_OASIS_ROOT=<oasis tree> \\
        python3 scripts/gen-historical-mechanism-flags.py > \\
        crates/backend/src/mock/historical_flags.rs

The OASIS root must contain:
    pkcs11-hist/v3.0/pkcs11-hist-v3.0.html         (function table)

Numeric values come from the umbrella workspace's 2.40 published header at
../doc/oasis-tcs-pkcs11/published/2-40-errata-1/pkcs11t.h, relative to this
repository. These external specification inputs are not vendored here.
"""

import os
import re
import sys
from pathlib import Path

# Column index (after the mechanism-name cell) -> CkMechanismFlags OR-set.
# Order matches the historical spec header:
#   Encrypt&Decrypt | Sign&Verify | SR&VR | Digest | GenKey/Pair | Wrap&Unwrap | Derive
COLUMN_FLAGS = [
    ["ENCRYPT", "DECRYPT"],
    ["SIGN", "VERIFY"],
    ["SIGN_RECOVER", "VERIFY_RECOVER"],
    ["DIGEST"],
    ["GENERATE", "GENERATE_KEY_PAIR"],
    ["WRAP", "UNWRAP"],
    ["DERIVE"],
]


def strip_tags(html: str) -> str:
    return re.sub(r"<[^>]+>", "", html).replace("&nbsp;", " ").replace("&amp;", "&").strip()


def parse_hist_flags(html_path: Path) -> dict[str, list[str]]:
    text = html_path.read_text(encoding="windows-1252", errors="replace")
    out: dict[str, list[str]] = {}
    for row in re.findall(r"<tr[^>]*>(.*?)</tr>", text, re.S):
        cells = [strip_tags(c) for c in re.findall(r"<td[^>]*>(.*?)</td>", row, re.S)]
        if not cells:
            continue
        name = cells[0]
        if not re.fullmatch(r"CKM_[A-Z0-9_]+", name):
            continue
        flags: list[str] = []
        for col, cell in enumerate(cells[1:]):
            if col < len(COLUMN_FLAGS) and cell.strip():
                flags.extend(COLUMN_FLAGS[col])
        # De-dup while keeping order.
        seen: set[str] = set()
        out[name] = [f for f in flags if not (f in seen or seen.add(f))]
    return out


def parse_header_values(header_path: Path) -> dict[str, int]:
    out: dict[str, int] = {}
    for m in re.finditer(
        r"#define\s+(CKM_[A-Z0-9_]+)\s+(0x[0-9A-Fa-f]+)UL", header_path.read_text()
    ):
        out[m.group(1)] = int(m.group(2), 16)
    return out


def main() -> int:
    oasis = os.environ.get("PKCS11_PROXY_NG_OASIS_ROOT")
    # Default to the umbrella cache when the env var is unset.
    repo = Path(__file__).resolve().parents[1]
    hist = None
    for base in filter(None, [oasis, str(repo.parent / "doc/pkcs11-oasis")]):
        cand = Path(base) / "pkcs11-hist/v3.0/pkcs11-hist-v3.0.html"
        if cand.exists():
            hist = cand
            break
    if hist is None:
        sys.stderr.write("historical spec not found (set PKCS11_PROXY_NG_OASIS_ROOT)\n")
        return 2
    header = repo / "../doc/oasis-tcs-pkcs11/published/2-40-errata-1/pkcs11t.h"
    if not header.exists():
        sys.stderr.write(f"2.40 header not found at {header}\n")
        return 2

    flags = parse_hist_flags(hist)
    values = parse_header_values(header)
    rows = []
    missing = []
    for name in sorted(flags):
        if name not in values:
            missing.append(name)
            continue
        rows.append((name, values[name], flags[name]))

    print("// @generated by scripts/gen-historical-mechanism-flags.py")
    print("// Source: OASIS PKCS#11 historical-mechanisms spec (pkcs11-hist v3.0)")
    print("// function table; numeric values from the 2.40 published header.")
    print("// DO NOT EDIT BY HAND — re-run the generator to refresh.")
    print("//")
    print(f"// {len(rows)} historical mechanisms grounded; "
          f"{len(missing)} lacked a 2.40 value and were skipped.")
    print("#![allow(clippy::unreadable_literal)]")
    print()
    print("use pkcs11_proxy_ng_types::{CkMechanismFlags, CkMechanismType};")
    print()
    print("/// Workflow flags for a legacy mechanism, transcribed from the")
    print("/// historical-mechanisms spec. `None` for mechanisms the spec does")
    print("/// not define (the mock keeps rejecting those).")
    print("pub(super) fn historical_workflow_flags(mech: CkMechanismType) -> Option<u64> {")
    print("    Some(match mech.0 {")
    for name, value, fl in rows:
        if not fl:
            expr = "0"
        else:
            # CkMechanismFlags consts are Self-typed (W1-C9-13); unwrap the
            # combined value to the u64 this table returns.
            expr = " | ".join(f"CkMechanismFlags::{f}" for f in fl)
            expr = f"({expr}).0"
        print(f"        // {name}")
        print(f"        {value:#010x} => {expr},")
    print("        _ => return None,")
    print("    })")
    print("}")
    if missing:
        sys.stderr.write(f"skipped (no 2.40 value): {', '.join(missing)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
